### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by anujmpec** [ionic2blueprints/ionic2-marketcloud#2]
I am getting following 

EXCEPTION: ReferenceError: BraintreePlugin is not defined

From where i can get it?

**Comment by fatmatto** [comment]
@anujmpec  I think the repository uses[ this package](https://github.com/braintree/braintree-web) to integrate Braintree, it can be installed with  "npm i braintree-web".

The BraintreePlugin is declared in the cart provider but in your case i think that it is a missing dependency problem, so I would try re-installing the plugin manually.

FYI we are building a ionic2-marketcloud starter using a more recent version of ionic2 at https://github.com/Marketcloud/ionic2-marketcloud-starter

**Comment by anujmpec** [comment]
I tried a lot ,, It worked now ,i checked ur theme ,it is just a starter , I am looking to something more but it is ok for just starting !!
